name: Build and Release App

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    strategy:
      matrix:
        os: [windows-latest]
        include:
          - os: windows-latest
            name: win
            ext: exe

    runs-on: ${{ matrix.os }}

    steps:
      # 检出分支
      - name: Checkout
        uses: actions/checkout@v3

      # 初始化Node环境
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # 初始化pnpm
      - name: pnpm setup
        uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: false

      # 加载pnpm缓存
      - name: Get pnpm store directory
        id: pnpm_cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm_cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      # 构建应用
      - name: Install dependencies and build
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          pnpm install
          pnpm build:${{ matrix.name }}

      # 新建release,如果有重复则跳过
      - name: Create Release
        uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false

      # 上传文件
      - name: Upload the release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GH_TOKEN }}
          files: |
            ./dist/**.${{ matrix.ext }}
            ./dist/latest.yml
